name: 'NVD clojure action'
description: |
  Run NVD clojure tool on codebase.  This action expects a leiningen
  managed project and a .nvd-config.json file.

runs:
  using: 'composite'
  steps:
    - id: cache-tstamp
      shell: bash
      run: |
        echo "::set-output name=out::$(/bin/date -u '+%Y%m')"

    - uses: actions/cache@v3
      with:
        path: "~/.m2"
        key: "${{ runner.os }}-nvd-clojure-action-${{ steps.cache-tstamp.outputs.out }}"

    - uses: DeLaGuardo/setup-clojure@master
      with: { cli: latest }

    - name: 'NVD check'
      shell: bash
      run: "${{ github.action_path }}/nvd-clojure.sh"
